---------------------
--- AUTOGENERATED ---
---------------------

hl.config({ autogenerated = false });

-----------------
--- VARIABLES ---
-----------------

local HOME = os.getenv("HOME");
local hyprlock_config = HOME .. "/.config/hyprlock/layouts/layout11.conf";

-----------------------------
--- ENVIRONMENT VARIABLES ---
-----------------------------

hl.env("XCURSOR_SIZE", "24");
hl.env("HYPRCURSOR_SIZE", "24");
hl.env("LANG", "en_US.UTF-8");

-- NVIDIA + HYPRLAND + SWWW FIX!
hl.env("WLR_NO_HARDWARE_CURSORS", "1");

----------------
--- MONITORS ---
----------------

hl.monitor({ output = "", mode = "preferred@60", position = "auto", scale = 1 });

---------------------
--- LOOK AND FEEL ---
---------------------

hl.config(
	{
		general =
		{
			gaps_in = 2,
			gaps_out = 3,

			border_size = 1,

			col =
			{
				active_border = "rgba(ffffffff)",
				inactive_border = "rgba(00000000)",
			},

			resize_on_border = true,

			allow_tearing = true,

			layout = "dwindle",
		},

		decoration =
		{
			rounding = 15,
			rounding_power = 2, -- Square = 0, Triangle = 1, Rounded = 2.

			active_opacity = 1.0,
			inactive_opacity = 1.0,

			shadow =
			{
				enabled = true,
				range = 4,
				render_power = 3,
				color = "rgba(1a1a1aee)"
			},

			blur =
			{
				enabled = true,
				size = 5,
				passes = 2,
				new_optimizations = true,
				ignore_opacity = false,
				vibrancy = 0.1696
			}
		},

		animations =
		{
			enabled = true;
		},

		dwindle =
		{
			preserve_split = true,
		},

		master =
		{
			new_status = "master",
		},

		misc =
		{
			force_default_wallpaper = -1,
			disable_hyprland_logo = false,
		},

		input =
		{
			kb_layout = "us,br",
			kb_variant = "",
			kb_model = "",
			kb_options = "grp:alt_shift_toggle",
			kb_rules = "",

			follow_mouse = 1,

			sensitivity = 0, -- -1.0 a 1.0, 0 significa nenhuma modificação.

			touchpad =
			{
				natural_scroll = true,
				scroll_factor = 0.3,
			}
		},

		debug =
		{
			damage_tracking = 0
		}
	}
);

----------------
--- GESTURES ---
----------------
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" });

---------------
--- PLUGINS ---
---------------

if hl.plugin.dynamic_cursors then
	hl.config(
		{
			plugin =
			{
				dynamic_cursors =
				{
					enabled = true,
					mode = "tilt",
					threshold = 2,
				}
			}
		}
	);
end

if hl.plugin.hyprcapture then
	hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd(HOME .. "/.local/bin/hyprcapture-ui --save-dir " .. HOME .. "/Pictures/Screenshots --clipboard 1 --save 0"));
	hl.bind("SUPER + Z", hl.dsp.exec_cmd(HOME .. "/.local/bin/hyprcapture-ui --save-dir " .. HOME .. "/Pictures/Screenshots --clipboard 1 --save 1"));
end

--------------
--- CURVES ---
--------------

--       NOME,                                           X0,   Y0,     X1,   Y1
hl.curve("easeOutQuint",   { type = "bezier", points = {{0.23, 1   }, {0.32, 1}} });
hl.curve("easeInOutCubic", { type = "bezier", points = {{0.65, 0.05}, {0.36, 1}} });
hl.curve("linear",         { type = "bezier", points = {{0,    0   }, {1,    1}} });
hl.curve("almostLinear",   { type = "bezier", points = {{0.5,  0.5 }, {0.75, 1}} });
hl.curve("quick",          { type = "bezier", points = {{0.15, 0   }, {0.1,  1}} });

------------------
--- ANIMATIONS ---
------------------

--             LEAF,                   ENABLED,        SPEED,        CURVE,                   [STYLE]
hl.animation({ leaf = "global",        enabled = true, speed = 1.00, bezier = "default"                       });
hl.animation({ leaf = "border",        enabled = true, speed = 1.00, bezier = "easeOutQuint"                  });
hl.animation({ leaf = "windows",       enabled = true, speed = 1.00, bezier = "easeOutQuint"                  });
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 1.00, bezier = "easeOutQuint", style = "slide" });
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.00, bezier = "linear",       style = "slide" });
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.00, bezier = "almostLinear"                  });
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.00, bezier = "almostLinear"                  });
hl.animation({ leaf = "fade",          enabled = true, speed = 1.00, bezier = "quick"                         });
hl.animation({ leaf = "layers",        enabled = true, speed = 1.00, bezier = "easeOutQuint"                  });
hl.animation({ leaf = "layersIn",      enabled = true, speed = 1.00, bezier = "easeOutQuint", style = "slide" });
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.00, bezier = "linear",       style = "slide" });
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.00, bezier = "almostLinear"                  });
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.00, bezier = "almostLinear"                  });
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.00, bezier = "almostLinear", style = "slide" });
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.00, bezier = "almostLinear", style = "slide" });
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.00, bezier = "almostLinear", style = "slide" });
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 1.00, bezier = "quick"                         });

-------------------
--- KEYBINDINGS ---
-------------------

hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"));
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("kitty --start-as fullscreen"));
hl.bind("SUPER + K", hl.dsp.exec_cmd("showmethekey-gtk -AC"));
hl.bind("SUPER + SHIFT + K", hl.dsp.exec_cmd("pkill showmethekey-gt"));
hl.bind("SUPER + Q", hl.dsp.window.close());
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock --config " .. hyprlock_config));
hl.bind("SUPER + F", hl.dsp.exec_cmd("kitty yazi " .. HOME));
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }));
hl.bind("SUPER + R", hl.dsp.exec_cmd("rofi -show drun"));
hl.bind("SUPER + P", hl.dsp.window.pseudo());
hl.bind("SUPER + N", hl.dsp.exec_cmd("xdg-open https://www.google.com/"));
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("iwgtk"));
hl.bind("SUPER + S", hl.dsp.exec_cmd("steam"));
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("spotify-launcher"));
hl.bind("SUPER + D", hl.dsp.exec_cmd("discord"));
hl.bind("SUPER + W", hl.dsp.exec_cmd("xdg-open https://web.whatsapp.com"));
hl.bind("SUPER + minus", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -1%"), { repeating = true });
hl.bind("SUPER + equal", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +1%"), { repeating = true });
hl.bind("SUPER + SHIFT + minus", hl.dsp.exec_cmd("brightnessctl set 1%-"), { repeating = true });
hl.bind("SUPER + SHIFT + equal", hl.dsp.exec_cmd("brightnessctl set 1%+"), { repeating = true });
hl.bind("SUPER + F1", hl.dsp.exec_cmd("hyprsunset --temperature 1000"));
hl.bind("SUPER + SHIFT + F1", hl.dsp.exec_cmd("pkill hyprsunset"));
hl.bind("SUPER + F2", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"));
hl.bind("SUPER + F3", hl.dsp.exec_cmd("waybar"));
hl.bind("SUPER + SHIFT + F3", hl.dsp.exec_cmd("pkill waybar"));
hl.bind("SUPER + F4", hl.dsp.exec_cmd("poweroff"));
hl.bind("SUPER + SHIFT + F4", hl.dsp.exec_cmd("pkill Hyprland"));
hl.bind("SUPER + F5", hl.dsp.exec_cmd("kitty wev"));
-- hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("hyprshot -m output --clipboard-only"));
-- hl.bind("SUPER + Z", hl.dsp.exec_cmd("hyprshot -m output"));
hl.bind("SUPER + X", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"));
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd("cliphist wipe"));
hl.bind("SUPER + RETURN", hl.dsp.window.fullscreen());

-- Navigate between windows with SUPER + arrow keys
hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }));
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }));
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }));
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }));

-- Navigate and move between workspaces with SUPER + [0-9]
for i = 1, 10 do
	local key = i % 10;

	hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }));
	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }));
end

-- Navigate between workspaces with mouse scroll.
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }));
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }));

-- Drag and resize windows with mouse buttons.
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true });
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true });

-- Laptop multimedia keys for volume and LCD brightness.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true });
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true });
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true });
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true });
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true });
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true });

-- Requires playerctl.
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true });
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true });
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true });
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true });

--------------------
--- WINDOW RULES ---
--------------------

hl.window_rule(
	{
		name = "fix-xwayland-drags",
		match =
		{
			class = "^$",
			title = "^$",
			xwayland = true,
			float = true,
			fullscreen = false,
			pin = false,
		},
		no_focus = true,
	},
	{
		name = "smtk-floating-window",
		match = { title = "Floating Window - Show Me The Key" },
		float = true,
		pin = true,
		no_focus = true,
		move = { 715, 820 },
		size = { 120, 50 },
	},
	{
		name = "rdr2",
		match = { class = "^(steam_app_1174180)$" },
		fullscreen = true
	}
);

-------------------------
--- AUTOSTART/STARTUP ---
-------------------------

hl.on(
	"hyprland.start",
	function()
		hl.exec_cmd("hyprlock --config " .. hyprlock_config)
		hl.exec_cmd("waybar")
		hl.exec_cmd("xdg-open https://www.google.com/")
		hl.exec_cmd("steam")
		hl.exec_cmd("discord")
		hl.exec_cmd("kitty hyprpm update")
		hl.exec_cmd("wl-paste --type text --watch cliphist store")
		hl.exec_cmd("wl-paste --type image --watch cliphist store")
	end
);

---------------
--- SOURCES ---
---------------

require(HOME .. "/.config/hypremoji/hypremoji");
